### ISSUE TITLE
Upload snapshots to bintray after build

### ISSUE THREAD

**Issue by arjantijms** [javaee-security-spec/soteria#10]
As part of a complete project setup we should have the snapshot builds available somewhere. Unfortunately travis doesn't store them, but there's an option to upload them to _somewhere_.

Since we're already using Bintray, this seems to be the most likely candidate to upload to. However, this upload is not entire trivial. There are at least 2 main methods, see:
- http://stackoverflow.com/a/30610859/472792
- https://docs.travis-ci.com/user/deployment/bintray

Also see:
- https://gist.github.com/letmaik/4060735

Plus, bintray/jfrog by default doesn't accept snapshots, but seems to need something called OJO/Artifactory:
- https://artifactory.jfrog.org/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org

cc

@rdebusscher @ivargrimstad @keilw

**Comment by keilw** [comment]
Please also see how that's done for JSR 354 with Travis: https://github.com/JavaMoney/jsr354-ri
I adapted that for JSR 363 where (I tried a few and that other than TravisCI works best) Circle-CI is used for the same purpose.

**Comment by arjantijms** [comment]
Thanks @keilw I'll use that as a guide.

@rdebusscher Did you check the "Host my snapshots ..." box when initially requesting access to jcenter?

At any length, at the package page (https://bintray.com/javaee-security-spec/maven/org.glassfish.soteria%3Asoteria) I requested access by clicking the _"
Stage snapshots on oss.jfrog.org"_ link there and providing the `org.glassfish.soteria` group id.

**Comment by rdebusscher** [comment]
@keilw made the initial repos at bintray, I just uploaded the artifacts to
it.

But I Don't remember anything seeing about snapshots (and didn't knew
either that they aren't accepting snapshots by default)

**Comment by arjantijms** [comment]
Ah ok. 

btw I now also requested the same OJO access for the API package, this time using the `javax.security` group id. Hopefully the multi-module structure of the project is not going to be a problem for the automatic upload/deployment later on, but we'll see.

**Comment by keilw** [comment]
They are, you have to define several repos including http://oss.jfrog.org/libs-snapshot/ for snapshots. See JSR 363 or 354. The milestones (for both) are currently uploaded to Bintray manually (not sure, guess it could be possible to automate it, too) but snapshots go to  JFrog OSS on every push to the repo.

**Comment by arjantijms** [comment]
>They are, you have to define several repos including http://oss.jfrog.org/libs-snapshot/ for snapshots. 

Hmmm, what's libs-snapshots for? I've defined 2 repos so far, one has been approved:

> *Your request to stage snapshots on oss.jfrog.org using the group ID 'org/glassfish/soteria' has been approved.*

**Comment by keilw** [comment]
That's the equivalent to e.g. Sonatype Snapshot or similar Snapshot repos at Apache. JCenter is the  official Bintray repo (like MavenCentral;-) while those are for snapshot deployments.

**Comment by arjantijms** [comment]
Ah, ok, it's also one of the entries in the Artifact Repository Browser: https://oss.jfrog.org/artifactory/webapp/#/artifacts/browse/tree/General/libs-snapshot

**Comment by arjantijms** [comment]
Ok, as of https://github.com/javaee-security-spec/soteria/commit/e901984e2a92dde8c5e897b3186403f8a01d3cbd snapshots are now being deployed on each push.

See:

* https://oss.jfrog.org/artifactory/oss-snapshot-local/org/glassfish/soteria/soteria/1.0-m02-SNAPSHOT/
* https://oss.jfrog.org/artifactory/oss-snapshot-local/javax/security/javax.security-api/1.0-m02-SNAPSHOT/

Some tweaking still needs to be done but the main thing works.

**Comment by arjantijms** [comment]
As of https://github.com/javaee-security-spec/soteria/commit/60e23406b2c0da847dd92988d1809297196e01f3 snapshots are not longer being deployed on each push. The idea is that eventually a Hudson instance will be set up by Oracle for this. "B" builds are now being deployed manually to maven.java.net.
