### ISSUE TITLE
Remove the internal API when API repo is stable

### ISSUE THREAD

**Issue by keilw** [javaee-security-spec/soteria#23]
Right now we still have an "api" module beside the https://github.com/javaee-security-spec/security-api repository. At least when EDR is out and there should be a milestone Maven artifact in JCenter and/or MavenCentral, this module should be droped in favor of using the actual API.

**Comment by arjantijms** [comment]
True, I had already modified this locally but never pushed it out (very,
very busy with updating/refactoring the Mojorra project).

Will push this as soon as I have some time, hopefully this weekend.

**Comment by ashri** [comment]
@arjantijms This issue can be closed as of today as you made these changes in commit [be2761a](https://github.com/javaee-security-spec/soteria/commit/be2761a6441a6784da563035c930a9eb5cffd3a9) on the 19th of March

**Comment by arjantijms** [comment]
Ok, thx for the reminder
