### ISSUE TITLE
Security-API combined with java.wx.rs REST API

### ISSUE THREAD

**Issue by sbaeurle** [javaee-security-spec/soteria#25]
Hello Guys,

first I would like to point out, how much I appreciated the work you did in simplifying and standardizing Security for Java EE 8. I'm currently working on an AuthenticationMechanism for somekind of basic REST-API developed with java.ws.rs. As your API makes things significatnly easier, I want to test out how it works out combined with java.ws.rs. Do you have some reference Implementations for combining your API with java.ws.rs or more generally,how far it's already implemented?

Currently I'm working with the default Implementation of your Basic-Authentication in Combination with an Embedded IdentityStore. They are both defined in the MainApplication, and everything works out quite fine, despite the fact, I'm not able to use it all, because all Requests are blocked due to Authentication. Also I'm not able to access the SecuriyContext to check  if the User is in a certain role.

So finally in advance: Thanks for your Support and Help

Greetings
Simon

Ps. I'll add my SourceCode in this post.

MainApplication
```
@BasicAuthenticationMechanismDefinition(
		realmName="test"
)

@EmbeddedIdentityStoreDefinition({ 
    @Credentials(callerName = "admin", password = "Passw0rd!", groups = { "admin", "superuser" }),
    @Credentials(callerName = "simon", password = "Passw0rd?", groups = { "superuser" }),
    @Credentials(callerName = "arjan", password = "secret3", groups = { "bar" }) }
)

@DeclareRoles({"admin", "superuser", "bar"})
@ApplicationPath("api/v1/")
public class MainApplication extends Application{

}
```

The Basic API Resource (only GET Implemented)
```
@Path("/user")
@RequestScoped
@PermitAll
public class AuthResource {
	
	@Inject
	private SecurityContext securityContext;
	
	@GET
	@Produces(MediaType.APPLICATION_JSON)
	public Response getUser() throws AuthenticationException{
		if(securityContext.isCallerInRole("superuser")){
		return Response.ok(new User("admin", "Passw0rd!", java.util.Arrays.asList("foo", "baa"))).build();
	}
		throw new AuthenticationException("User not Permitted!");
	}
}
```

WEB-XML
```
<!DOCTYPE web-app PUBLIC
 "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
 "http://java.sun.com/dtd/web-app_2_3.dtd" >

<web-app>
  <display-name>Archetype Created Web Application</display-name>
  
  <login-config>
  	<auth-method>BASIC</auth-method>
  	<realm-name>test</realm-name>  	
  </login-config>
</web-app>
```

**Comment by sbaeurle** [comment]
Somehow the Code Styling is not working very well :/

**Comment by keilw** [comment]
That in GitHub here I asssume?;-)

**Comment by sbaeurle** [comment]
Sorry did not find one :(

**Comment by keilw** [comment]
I think this does the trick, the character is weird, I believe on average German keyboards it is `SHIFT` next to "?" or "ß" ;-)

**Comment by keilw** [comment]
What is the exception or stacktrace you're getting?

**Comment by sbaeurle** [comment]
I'm getting a CDI Exception, something with the injection of the SecurityContext works out wrong :)

**Comment by keilw** [comment]
I am a little less deep in the CDI EG than this one (and a few others) but first of all, what are the CDI version, implementation (likely Weld, but there are a few others) and container, e.g. Glassfish/Payara, TomEE, etc. ?

**Comment by keilw** [comment]
It's often blank but CDI containers up to CDI 1.2 usually insist you put beans.xml into the right place. META-INF or for some types of apps it may also be in a different place, but e.g. (working) microprofile samples I helped with use META-INF, see https://github.com/eclipse/microprofile-samples/blob/master/microprofile-sample-canonical/src/main/resources/META-INF/beans.xml

**Comment by sbaeurle** [comment]
I have to just point out, that this CDI approach is not my prefered approach. I'm just going this way, cause I couldn't figure out how to combine those Annotations form java.ws.rs like ``` @RolesAllowed("admin") ´´´
with the API. Therefore I went this way, but I would still prefer the JAX-RS approach.

[https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.nd.doc/ae/twbs_jaxrs_impl_securejaxrs_annotations.html](url)

**Comment by sbaeurle** [comment]
I have a beans.xml in WEB-INF, but I tought the Injection of the SecurityContext would be managed by the API, as it is described in one of your docs.

**Comment by keilw** [comment]
We're considering such annotations, but right now I can't promise they will come in 1.0. Standardizing `SecurityContext` is the most important goal. Then look at how different vendors and users/developers use these kinds of annotations, so we may come to a common denominator, but at ther very least that might have to wait for a MR of this JSR or a new one.

**Comment by sbaeurle** [comment]
Okay, so currently there is no such easy way like combining these Frameworks/APIs together, however it could make it to final 1.0 release or a future major update. Thanks for your help, I will go the CDI Way then.

**Comment by rdebusscher** [comment]
Hi,

I think there is a mix of a few concepts which makes that your application isn't working. JAX-RS endpoints aren't normally annotated with CDI scopes.
And Java EE Security API integrates with the low level things, so you can use SecurityContext from JAX-RS.

Have a look at this class
https://github.com/rdebusscher/soteria-jwt/blob/master/test-jws/src/main/java/be/rubus/soteria/jwt/test/HelloResource.java to have the JAX-RS securityContext available.

As you can see, there is nothing specific of Java EE Security in this class, and yet the endpoint is under control of Soteria (with a JWT token in this case but that doesn't matter).

When you define the JAX-RS endpoint as an EJB bean (with @Singleton for example), you even should be able to use the  @RolesAllowed annotation. (whatch out for concurrency then, use also the @Lock for example)

Hope this puts you in te right direction for your use case.

**Comment by keilw** [comment]
Thanks for the additional example and suggestions.
I added issues to https://github.com/javaee-security-spec/security-examples and a milestone **EDR 1** like Soteria already had. Ideally some examples should highlight how to use the API in different scenarios, Servlet/JSP, REST/MVC and maybe others.

**Comment by sbaeurle** [comment]
@rdebusscher First of all, thanks for your detailled answer. I tried to achieve the context with ````@Context SecurityConetex context```, but every time I want to access any method or get/setter to give back something, there is an Exception thrown. Also to for the usage of ```@RoleAllowed``` shouldn't there be some roles declared in any config file, because for me it is not working. So far all calls to the api return HTTP:200, if you do not try to authenticate via Basic Authentication, but when you add a Authorization Header your Request is blocked.

**Comment by sbaeurle** [comment]
So probably I declared something wrong for the AuthenticationMechnism, because it does not prompt me to authenticate and the SecurityContext ist empty as well. Maybe you cannot annotate those two things in the Application Class 😄

**Comment by rdebusscher** [comment]
I created a small test application to verify your use case.

And indeed, when you use the Basic authentication mechanism, there is no prompt when the _Authorization Header_ is not set (it works when present)

It seems that WildFly JASPIC doesn't mark the request as protected (even when I add a _<security-constraint>_ in web.xml) and thus Soteria isn't responding with a 401 status and a header of _WWW-Authenticate_.

We need to check other servers if they behave in the same way.

**Comment by arjantijms** [comment]
Hi,

Thanks for looking at the Security JSR ;)

Without going into the specific issues, as a general point it would
probably be good to have a JAX-RS based example / test in the main project.
Something like this:
http://arjan-tijms.omnifaces.org/2014/11/header-based-stateless-token.html

Additionally, it's kind of a shame that as one of the few servers
JBoss/WildFly still requires JASPIC to be activated via a vendor specific
xml file in the war. They mentioned years ago that this should be
addressed, and they certainly took big steps to address this (kudos to
them), but as it stands the activation is still needed up till now.

Since Red Hat is on board of the Security JSR we should, I think, once
again ask them to address this once and for all.

Outside of our direct control, but it would help a lot of JAX-RS also
started to migrate away from their own bean model and started to adopt CDI
even more. That was one of the things under consideration for EE 8, but not
much has happened there for JAX-RS it seems.

Kind regards,
Arjan Tijms

**Comment by sbaeurle** [comment]
Thanks for you answers, but somehow it still is not working out like it should. So far, I activated JAPISC in my jboss-web.xml by adding 
`<?xml version="1.0"?>
<jboss-web>
   <security-domain>jaspitest</security-domain>
</jboss-web>`

As far as it goes, the Application now blocks out all attempts, without sending back a WWW-Auth Header.
The funny thing is, if you remove the  `<security- domain>jaspitest</security-domain>` you can do API calls, but only if your not sending a Authentication with the Request :D 

Currently I have: 

```
@BasicAuthenticationMechanismDefinition(
		realmName="test"
)

@EmbeddedIdentityStoreDefinition({ 
    @Credentials(callerName = "admin", password = "Passw0rd!", groups = { "admin", "superuser" }),
    @Credentials(callerName = "simon", password = "Passw0rd?", groups = { "superuser" }),
    @Credentials(callerName = "superuser", password = "Passw0rd?!", groups = { "superuser" }) }
)


@ApplicationPath("api/v1/")
@DeclareRoles({"admin", "superuser"})
public class MainApplication extends Application{

}
```

```
@Path("/user")
@RequestScoped
public class UserResource {
	
	@GET
	@Produces(MediaType.APPLICATION_JSON)
	public Response getUser(@Context SecurityContext context){		
		return Response.ok(context.getCallerPrincipal()).build();
	}
	
	@POST
	@Consumes(MediaType.APPLICATION_JSON)
	public Response postUser(User user){
		return Response.ok(user).build();
	}
	
	@PUT
	public Response putUser(){		
		return Response.status(Status.METHOD_NOT_ALLOWED).build();
	}
	
	@DELETE
	public Response deleteUser(User user){
		return Response.status(Status.METHOD_NOT_ALLOWED).build();
	}
}
```

The only Response I get :

```
<html>
    <head>
        <title>Error</title>
    </head>
    <body>Unauthorized</body>
</html>
```

**Comment by keilw** [comment]
Unless there is anything proprietary or confidential, do you think you could make relevant parts available so @arjantijms, @rdebusscher, myself or others could give it a try? Some (at least 3 EG members of JSR 375) will meet at JavaLand next week, including Spec Leads of CDI, Bean Validation, MVC and a few others. I am not sure what they planned to replace it but there was a Java EE 8 hackathon with @AdamBien planned which he could not make it to. There are plenty of community activities, so we can look at real world use cases and challenges like this would be a great opportunity to improve Security API and other EE 8 JSRs.

**Comment by keilw** [comment]
I'll put something up in https://github.com/javaee-security-spec/security-examples later. There is even a script but not sure, if it still works. As soon as a module exists, please feel free to propose a PR (anybody who has something to contribute) At least the examples or proposals are not restricted to EG members.

**Comment by rdebusscher** [comment]
I'll put today my test case I had prepared yesterday on Github. 

Post the Repository URL when done.

**Comment by keilw** [comment]
Sure, as EG member you should have the necessary credentials to add a module. Tell @arjantijms me or Will if you have problems.

**Comment by rdebusscher** [comment]
See here https://github.com/javaee-security-spec/security-examples/tree/master/rest-basic-example

**Comment by sbaeurle** [comment]
Mostly all relevant parts are already made avalaible in this post, but somehow I can create pull request in any GIT-Repository you want, and add my code there. So when I look at the example code of @rdebusscher it's somehow obvious why my example webapp did not work correct. As far as I see, there is no support for Delaring the IdentityStore as well as the AuthMechanism outside a HttpServlet. I declared it in the MainApplication, maybe this was the Problem.

**Comment by keilw** [comment]
Thanks.

>which only works on WildFly 10

Hope we can broaden that a bit?;-)

**Comment by rdebusscher** [comment]
Added the web.wml specific for Liberty and Payara. TomEE works without any additional config.

Didn't test these other servers but should not be an issue on them.

**Comment by rdebusscher** [comment]
@sbaeurle 

Location of the annotations for identityStore and authenticationMechanism are picked up on any CDI class, not only on Servlet.

The main difference with your code is the absence of the CDI scope on the JAX-RS endpoint.

But my example isn't working either when you don't specify the Header! this is an issue on WildFly it seems.

**Comment by keilw** [comment]
Thouth it should be rather similar to Payara Glassfish 5 is probably the most important one ;-)

**Comment by sbaeurle** [comment]
Jup, it's what @arjantijms wrote above in his post. You need to add JAPIC to you WildFly 10 Server. 

> The main difference with your code is the absence of the CDI scope on the JAX-RS endpoint.

yeah, but shouldn't there be no complications with ````@RequestScoped``` above your JAX RS Resource?
I'm not that familiar with CDI, so I'm just making assumptions. 

But still, I adopted to you example, created a basic servlet and modified my Resource the same manner your Resource is implemented, but somehow it is not working out. When I try to test my small API with Postman, and just add a BASIC Authentication Header, it still says, I'm not authenticated.

**Comment by sbaeurle** [comment]
I did some research, the actual Exception ist:
`java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.lang.ClassNotFoundException: Dummy from [Module "deployment.jaxrs.api.war:main" from Service Module Loader]`
I think this could be caused by some malformed xml file (either standalone or jboss-web) for activating JASPIC.

**Comment by sbaeurle** [comment]
Hey Guys, sorry for beeing so late, but i finally managed to create a Repository with my Code in it.
You can find it there: [https://github.com/sbaeurle/soteriatest.git](url)

The Problem, when using in Combination with RolesAllowed, that you need to specific use a Implmentation of JAX RS, to use RolesAllowed correctly (for example JERSEY)

Again, thanks for your help :)
