### ISSUE TITLE
Publish m03 to BinTray?

### ISSUE THREAD

**Issue by ggam** [javaee-security-spec/soteria#32]
Seems like only m01 was uploaded to BinTray. Could anyone please upload the recently tagged m03?

Also, some instructions (repository URL, Maven coordinates) could be added to the readme to facilitate testing. I can take care of it.

**Comment by arjantijms** [comment]
Indeed, this in outstanding todo item. m03 is not uploaded because the
build fails, which is because the API was recently split off and not
published independently.

Hope to find some time to do this today, as it of course should not be in
this state.

**Comment by keilw** [comment]
I'm at JavaLand, probably able to do it later in the day after our own sessions. We hope to also do some "Adopt" session with me, @rdebusscher if he can and @ivargrimstad all EG members who are here.

**Comment by arjantijms** [comment]
I uploaded the API jar manually the other day, but this should be automated
again.

**Comment by keilw** [comment]
Where, it is not in Bintray right now? In either case, we should tag `m03` both here and in https://github.com/javaee-security-spec/security-api/releases

**Comment by arjantijms** [comment]
Hi,

As m03 is a snapshot, it's in the snapshot repo:

https://oss.jfrog.org/artifactory/oss-snapshot-local/javax/security/javax.security-api/1.0-m03-SNAPSHOT/

Kind regards,
Arjan Tijms

**Comment by keilw** [comment]
As m03 has been out for a while I think this can be closed.
