### ISSUE TITLE
How do you we see Soteria tracking the specification and progressing towards 1.0

### ISSUE THREAD

**Issue by ashri** [javaee-security-spec/soteria#59]
Hi,

Now that the specification has reached Public Review Draft I am wondering how everyone sees Soteria tracking against its changes and what still needs to be done to complete the RI.

I have a number of questions around this:

- Are we matching the version numbers of the specification? For example it went to m05-SNAPSHOT, does that mean Soteria should be updated to m05-SNAPSHOT?

- How aggressive are we in keeping up to date with the spec? Is it better to be aggressive and track all changes or better to wait until the specification publishes the final version before making the changes all at once?

- Now that the mailing list is active should I me posting these questions there rather than Github? Is the mailing list even a suitable venue for discussion of Soteria or is it more focused on the specification only?

If these questions seem obvious or trivial, but as a first time contributor to a JSR I am interested in getting involved in the most friction-free way possible.

**Comment by ggam** [comment]
Hi,

> Are we matching the version numbers of the specification? For example it went to m05-SNAPSHOT, does that mean Soteria should be updated to m05-SNAPSHOT?

I don't know for sure, but I think yes, its versions are aligned.

> How aggressive are we in keeping up to date with the spec? Is it better to be aggressive and track all changes or better to wait until the specification publishes the final version before making the changes all at once?

They are basically synced, so people can test it and give feedback.

> Now that the mailing list is active should I me posting these questions there rather than Github? Is the mailing list even a suitable venue for discussion of Soteria or is it more focused on the specification only?

I think the ML is better suited for spec (text or API) related questions, but the RI is also part of the spec. I'd post Soteria specific questions here on GitHub (the EG is already monitoring it).

**Comment by ashri** [comment]
Thanks for the response and I will follow the advice
