### ISSUE TITLE
RemeberMe : Cookie.setHttpOnly(false) never called

### ISSUE THREAD

**Issue by marco76** [javaee-security-spec/soteria#63]
The annotation ```RememberMe``` allows to set the following flags: ```cookieSecureOnly```, ```cookieHttpOnly```.

_Result expected_
```Cookie#isHttpOnly``` of the cookie passed to a client can be false allowing JS clients to read its content.

_Probable Bug_
Some flags of ```RememberMe``` are never used to set the properties of the Cookie sent to the client:

-The [```saveCookie```](https://github.com/javaee-security-spec/soteria/blob/master/impl/src/main/java/org/glassfish/soteria/cdi/RememberMeInterceptor.java#L166) method in ```RememberMeInterceptor``` doesn't pass the parameters to CookieHandler.

-CookieHandler set [```cookie.setHttpOnly(true);```](https://github.com/javaee-security-spec/soteria/blob/master/impl/src/main/java/org/glassfish/soteria/servlet/CookieHandler.java#L56)

**Comment by arjantijms** [comment]
Thanks for the report, indeed, this still has to be implemented (and a test added for it as well).

**Comment by arjantijms** [comment]
Implemented this and provided a test for it. Should now work, but let me know if there are still issues.

**Comment by zjmtlab** [comment]
Hi Arjan,  the HttpOnly have been implemented now,  is the secureOnly also been implemented too? Want to confirm it. Thanks!

**Comment by arjantijms** [comment]
>Hi Arjan, the HttpOnly have been implemented now, is the secureOnly also been implemented too? Want to confirm it. Thanks!

Sorry, that one has not yet been done yet, I'll create a new issue for it. Thanks a bunch for the reminder!
