### ISSUE TITLE
AuthException in case of auth failure.

### ISSUE THREAD

**Issue by sameer-pandit** [javaee-security-spec/soteria#65]
I am curious about the AuthException from HAMs in soteria/tests. Many of the test samples have the below code in their HAMs. e.g. app-custom/src/main/java/org/glassfish/soteria/test/TestAuthenticationMechanism.java
```java
if (result.getStatus() == VALID) {
  ...
}else{
  throw new AuthException("Login failed");
}
```
As per the JASPIC spec AuthException is thrown When the message processing failed without establishing a failure response message.
The above case and similar others are case where there is authentication failure and not an exception. should this be changed to 
```java
httpMessageContext.responseUnAuthorized();
```
?
Currently on auth failure, one would expect to get 401 but with testing with glassfish, we are seeing 500 Internal error as the HAM throws AuthException. Or does this needs to be handled appropriately from glassfish side ?

**Comment by arjantijms** [comment]
Hi Sameer,

I was just thinking about this the other week too. 

My feeling says the server should return an appropriate response here on behalf of the SAM or HAM, so setting a 401 in the response and rendering a server specific unauthorized page.

This is what JBoss/WildFly for instance is doing.

To be totally honest, I'm not 100% sure about this, so to get this absolutely right please contact Ron Monzillo within Oracle.

For now I think it's best to change the samples to behave like you suggested indeed, so returning `httpMessageContext.responseUnAuthorized();`.

**Comment by arjantijms** [comment]
Sameer, I committed the change, and all tests pass. Let me know if there's anything else. Will close the issue for now, but if there's more it can always be re-opened.

**Comment by wmhopkins** [comment]
Technically, I think the correct should probably depend on the nature of the problem that resulted in an exception. A HAM/SAM should probably not throw an exception to indicate a "normal" result -- like authentication failed -- instead, it should always establish a response and then return the appropriate status.

An exception would therefore be indicative of a real problem -- a NullPointerException, or UnsupportedException, or IOException, or IllegalArgumentException, etc. -- i.e., the type of problem that status 500 internal server error is supposed to be used for.

That said, it would be better not to "leak" any information that could give an attacker clues about how the authentication processing works or what inputs can trigger an internal error. From that point of view, returning 401 Unauthorized, like JBoss/WildFly seems like best behavior.

I don't think JASPIC cares which error is returned, as long as it's legitimate.
