### ISSUE TITLE
security-api -> responseUnAuthorized: rename to responseUnauthorized

### ISSUE THREAD

**Issue by vsmid** [javaee-security-spec/soteria#68]
This is actually not connected to implementation but to api. 

Consider renaming method responseUnAuthorized to responseUnauthorized since unauthorized should be a single word.

javax.security.enterprise.authentication.mechanism.http.HttpMessageContext#responseUnAuthorized()

**Comment by arjantijms** [comment]
+1 from me, good catch!

**Comment by arjantijms** [comment]
Half of the work has been pushed, now we have to wait for the PR on the API repo to be merged in.

**Comment by arjantijms** [comment]
API PR has been merged as well now, closing this issue.
