### ISSUE TITLE
Align code with api:1.0-b06

### ISSUE THREAD

**Issue by rdebusscher** [javaee-security-spec/soteria#69]
There is quite an amount of restructuring of the code in the API
- new maven Group and ArtefcatId
- Classes moved to other packages

Soteria needs to be updated for these changes.

**Comment by rdebusscher** [comment]
Refactoring done, but some tests are failing now.

I need to investigate it before PR can be submitted

**Comment by rdebusscher** [comment]
The hardcoded package within a String in org.glassfish.soteria.authorization.spi.impl.SubjectParser#doGetCallerPrincipalFromPrincipals was the cause.

**Comment by arjantijms** [comment]
Thanks for looking at this Rudy!

SubjectParser would indeed not survive this kind of refactoring automatically. I had hoped to be able to standardise what SubjectParser does (via the portable group to role mapper epic), but unfortunately this didn't happen.

Going forward we may be able to break up SubjectParser in actually API jars for each supported server and include a single jar of those based on which server is tested. This is somewhat more work and I haven't gotten to it yet.

**Comment by rdebusscher** [comment]
That is indeed a good idea.

Although there would not be a lot of code within the server specific jar, it allows easier integration of Soteria within the actual servers. And vendors can create easier extensions.

I'll create an issue for this kind of SPI.
