### ISSUE TITLE
With multiple identity stores getting groups does not have to be in order

### ISSUE THREAD

**Issue by wxwesther** [javaee-security-spec/soteria#77]
For the latest SecurityAPI interface, below is getCallerGroup definition in IdentityStore.java. A set returned in getCallerGroup and the groups are not in order.
     Set<String> getCallerGroups(CredentialValidationResult validationResult)

Here,  I am wondering why we change List<> to Set<> in the new interface? Is it necessary to return a list in some order? ( alphabetical order or a based on the IDStore priority order? )

If we decide return set<> groups, then I don't think we need to emphasize the priroty order in below spec saying. What do you think?
  Spec says: 3.2.4. Handling Multiple Identity Stores
     ...
    • Call the getCallerGroups() method on all available IdentityStore beans that declared only the PROVIDE_GROUPS validation type, in the order induced by the return value of the getPriority() method of each IdentityStore, passing in the CredentialValidationResult obtained during the previous phase. Add the groups returned by each call to the set of accumulated groups.

Thanks!

**Comment by ggam** [comment]
As I understand it, order is only mandated for identity validation. Validation stops when the first IdentityStore validates authentication. It saves the (potential) groups returned by that store, and then it calls all the identity stores that are only capable of providing groups, in an unspecified order, adding its returned groups to the bag.

**Comment by arjantijms** [comment]
>Here, I am wondering why we change List<> to Set<> in the new interface?

There was some debate about this. A list is more common in many APIs, but the groups are supposed to be unique (no duplicates), and a set better communicates that.

An ordering of the groups within the set does not matter for any of the algorithms in JSR 375.

**Comment by arjantijms** [comment]
Is there anything else that should be explained or done here?

**Comment by wxwesther** [comment]
Thanks ggam and arjantijms for your quick response. 
It is reasonable to avoid the duplicate group by using the Set.  

Then it is better to remove the saying " in the order induced by the return value of the getPriority() method of each IdentityStore"  in Section 3.2.4. Handling Multiple Identity Stores

"... Call the getCallerGroups() method on all available IdentityStore beans that declared only the PROVIDE_GROUPS validation type, **_in the order induced by the return value of the getPriority() method of each IdentityStore_**, passing in the CredentialValidationResult obtained during the previous phase. Add the groups returned by each call to the set of accumulated groups..."

**Comment by ggam** [comment]
I didn't notice the statement in the spec was also about the groups. I think you're right it can be removed. If you have already signed the Oravle CLA or you are a JCP member, could you provide a PR on the spec repo?

**Comment by arjantijms** [comment]
PR created here: https://github.com/javaee-security-spec/security-spec/pull/7

**Comment by wmhopkins** [comment]
I commented also on the PR, but I'm wondering if we might want to leave this the way it is. Ordering the invocations is not necessary as a means to order the resulting groups, but, equally, ordering by priority is harmless, and might provide some value. It's only a requirement for the default handler, but provides clarity and predictability about the handler's behavior. It supports the principle of least surprise, by ensuring that identity stores are always invoked in priority order. It seems odd to me that id stores would be invoked in priority in some cases, but not others, and I suspect it would surprise many id store authors.

**Comment by wmhopkins** [comment]
The upshot with this is we've decided to leave it as is. While there is no requirement, strictly speaking, to fetch groups in a particular order, there is value in having known, predictable behavior, as well as consistent behavior between the validate and provide_groups phases. Since there is equally no harm in fetching groups in an ordered way, this will be left as is.
