### ISSUE TITLE
Is there any requirement that which types of HashEncoding and hashAlgorithm supported in DatabaseIdentityStore?

### ISSUE THREAD

**Issue by wxwesther** [javaee-security-spec/soteria#83]
The property of DatabaseIdentityStore annotation is string instead of enum, then I am confused what should I set for the two properties?

**Comment by rdebusscher** [comment]
See also #48.

**Comment by wmhopkins** [comment]
Closing this as a duplicate issue; the solution will be driven via [#48](https://github.com/javaee-security-spec/soteria/issues/48)
