### ISSUE TITLE
dependency collision: cdi-2.0 & Soteria

### ISSUE THREAD

**Issue by vsmid** [javaee-security-spec/soteria#88]
I tried to use cdi-2.0 javax.enterprise.event.Event#fireAsync with Soteria. 

When I added a class which implements javax.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism I stumbled upon a problem. 

It turns out that method
javax.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism#validateRequest throws javax.security.auth.message.AuthException for which javaee-api-7.0 dependency is needed.

When I added javaee-api-7.0 dependency I could no longer access javax.enterprise.event.Event#fireAsync. That is because with javaee-api-7.0 and cdi-api-2.0 I now have two javax.enterprise.event.Event classes on my classpath with the same package and class name.

Since new security-api provides (and Soteria uses) javax.security.enterprise.AuthenticationStatus instead javax.security.auth.message.AuthStatus from javaee-api-7.0 maybe it would be a good idea to create javax.security.enterprise.AuthenticationException inside new security-api. For this part, this would remove javaee-api-7.0 as needed dependency.

Proposed method signature would then be:

javax.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism#validateRequest(HttpServletRequest hsr, HttpServletResponse hsr1, HttpMessageContext hmc) throws javax.security.enterprise.AuthenticationException;

The same could then be applied to:

javax.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism#secureResponse(HttpServletRequest hsr, HttpServletResponse hsr1, HttpMessageContext hmc) throws javax.security.enterprise.AuthenticationException;

**Comment by rdebusscher** [comment]
I think we should keep the Java EE7 compatibility.

But in case you want to try it out with CDI 2 (for example WildFly 10/11 with a patched Weld) you can use the following dependencies


        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>javax.enterprise</groupId>
            <artifactId>cdi-api</artifactId>
            <version>2.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.2-b02</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>javax.security.auth.message</groupId>
            <artifactId>javax.security.auth.message-api</artifactId>
            <version>1.1</version>
            <scope>provided</scope>
        </dependency>


This combination removes the requirement to depend on Java EE 7 and allows you to use CDI 2. The last dependency contains the JASPIC specific things.

**Comment by vsmid** [comment]
Thanks for the suggestion.

Compatibility wise it is ok. But i think it would be a good idea to decouple things as much as possible.

Also, security-api does not use AuthStatus from javaee-api-7.0 but has created its own AuthenticationStatus. At the same time it uses AuthException from javaee-api-7.0.  That is a part which is confusing to me, hence my proposal😊

**Comment by rdebusscher** [comment]
If I remember correctly the discussion, the AuthException from JASPIC was kept because Security API (and Soteria) is built on top on of JASPIC. And keeping that exception would allow us to JASPIC handle our exceptions.

**Comment by keilw** [comment]
Do we really want to keep Java EE 7 compatibility for a JSR that targets Java EE 8?

**Comment by rdebusscher** [comment]
It allows a faster adoption, I guess.

Otherwise, developers have to wait until the EE8 compliant version of their favorite application server is available. (which could take a while as the past has learned us)

And since we don't depend on any Java EE 8 specific things (using BeanConfigurator of CDI 2.0 could be an option instead of our own version) I don't see any reason why we shouldn't do it.

**Comment by arjantijms** [comment]
We could have used things from Java EE 8, but eventually we didn't, so I
don't think there's any need to abandon Java EE 7 compatibility at this
point.

The issue the TS ran into would also happen when Servlet 4 would be used
for instance.

An alternative to what Rudy proposed is excluding CDI using the maven
excludes tag within the java ee 7 dependency.

Kind regards,
Arjan Tijms






On Fri, Jun 23, 2017 at 11:08 AM, Rudy De Busscher <notifications@github.com
